// Package normalize converts source-specific observations into canonical ones.
//
// It runs directly after validation and before enrichment on purpose: its
// output depends only on the raw message and the mapping table, never on
// mutable inventory, so the normalized stream is a pure function of the raw
// stream and can be regenerated by replay.
//
// Mappings are declarative (rename, scale, enum-to-bool, label mapping). There
// is deliberately no expression language; anything more exotic belongs in a
// JavaScript transform, which is validated and sandboxed.
package normalize

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/alfscherer/infra-observer/internal/domain"
)

// Kinds of value conversion.
const (
	KindIdentity = "identity" // value unchanged
	KindScale    = "scale"    // number * factor
	KindBool     = "bool"     // number in true_values -> true
	KindEnum     = "enum"     // number -> string via map
)

// Convert describes how the raw value becomes the canonical value.
type Convert struct {
	Kind       string            `yaml:"kind"`
	Factor     float64           `yaml:"factor"`      // scale
	TrueValues []float64         `yaml:"true_values"` // bool
	Map        map[string]string `yaml:"map"`         // enum: "2" -> "down"
}

// Mapping is one raw-to-canonical rule.
type Mapping struct {
	Raw     string            `yaml:"raw"`
	Metric  string            `yaml:"metric"`
	Unit    string            `yaml:"unit"`
	Convert Convert           `yaml:"convert"`
	Labels  map[string]string `yaml:"labels"` // raw label -> canonical label; when set, unlisted labels are dropped
}

type document struct {
	Mappings []Mapping `yaml:"mappings"`
}

// Normalizer applies mappings. It is immutable after construction and safe
// for concurrent use.
type Normalizer struct {
	byRaw map[string]Mapping
}

var metricRe = regexp.MustCompile(`^[a-z][a-z0-9_]*(\.[a-z0-9_]+)*$`)

// LoadFile reads and validates a mapping file.
func LoadFile(path string) (*Normalizer, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read normalization: %w", err)
	}
	n, err := Parse(raw)
	if err != nil {
		return nil, fmt.Errorf("normalization %s: %w", path, err)
	}
	return n, nil
}

// Parse decodes mappings strictly and validates them.
func Parse(raw []byte) (*Normalizer, error) {
	var doc document
	dec := yaml.NewDecoder(bytes.NewReader(raw))
	dec.KnownFields(true)
	if err := dec.Decode(&doc); err != nil {
		return nil, err
	}
	n := &Normalizer{byRaw: make(map[string]Mapping, len(doc.Mappings))}
	var problems []string
	for i, m := range doc.Mappings {
		if m.Convert.Kind == "" {
			m.Convert.Kind = KindIdentity
		}
		where := fmt.Sprintf("mappings[%d] (%s)", i, m.Raw)
		switch {
		case m.Raw == "":
			problems = append(problems, fmt.Sprintf("mappings[%d]: raw is required", i))
		case !metricRe.MatchString(m.Metric):
			problems = append(problems, where+": canonical metric must be lower-case dotted, e.g. system.cpu.utilization")
		}
		if _, dup := n.byRaw[m.Raw]; dup {
			problems = append(problems, where+": duplicate mapping for raw metric")
		}
		switch m.Convert.Kind {
		case KindIdentity:
		case KindScale:
			if m.Convert.Factor == 0 {
				problems = append(problems, where+": scale needs a non-zero factor")
			}
		case KindBool:
			if len(m.Convert.TrueValues) == 0 {
				problems = append(problems, where+": bool needs true_values")
			}
		case KindEnum:
			if len(m.Convert.Map) == 0 {
				problems = append(problems, where+": enum needs a map")
			}
		default:
			problems = append(problems, fmt.Sprintf("%s: unknown convert kind %q", where, m.Convert.Kind))
		}
		n.byRaw[m.Raw] = m
	}
	if len(problems) > 0 {
		return nil, domain.Errorf(domain.CategoryValidation, "%s", strings.Join(problems, "; "))
	}
	return n, nil
}

// Result reports what happened to an observation.
type Result int

const (
	Mapped      Result = iota // a mapping applied
	Passthrough               // no mapping; observation returned unchanged
)

// RawMetrics lists every raw metric with a mapping, sorted.
func (n *Normalizer) RawMetrics() []string {
	out := make([]string, 0, len(n.byRaw))
	for k := range n.byRaw {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// Normalize returns the canonical form of o. The input is not modified. A
// value that cannot be converted is a validation error: retrying will not fix it.
func (n *Normalizer) Normalize(o domain.Observation) (domain.Observation, Result, error) {
	m, ok := n.byRaw[o.Metric]
	if !ok {
		return o, Passthrough, nil
	}
	out := o.Clone()
	v, err := convert(m.Convert, o.Value)
	if err != nil {
		return o, Mapped, domain.Errorf(domain.CategoryValidation, "normalize %s (%s): %v", o.Metric, o.ObservationID, err)
	}
	out.Metric, out.Value = m.Metric, v
	if m.Labels != nil {
		labels := make(map[string]string, len(m.Labels))
		for from, to := range m.Labels {
			if val, ok := o.Labels[from]; ok {
				labels[to] = val
			}
		}
		out.Labels = labels
	}
	if out.Metadata == nil {
		out.Metadata = map[string]string{}
	}
	out.Metadata["raw_metric"] = o.Metric
	if m.Unit != "" {
		out.Metadata["unit"] = m.Unit
	}
	return out, Mapped, nil
}

func convert(c Convert, v any) (any, error) {
	switch c.Kind {
	case KindIdentity:
		return v, nil
	case KindScale:
		f, ok := number(v)
		if !ok {
			return nil, fmt.Errorf("scale needs a numeric value, got %T", v)
		}
		return f * c.Factor, nil
	case KindBool:
		if b, ok := v.(bool); ok {
			return b, nil
		}
		f, ok := number(v)
		if !ok {
			return nil, fmt.Errorf("bool conversion needs a numeric value, got %T", v)
		}
		for _, t := range c.TrueValues {
			if f == t {
				return true, nil
			}
		}
		return false, nil
	case KindEnum:
		f, ok := number(v)
		if !ok {
			return nil, fmt.Errorf("enum needs a numeric value, got %T", v)
		}
		s, ok := c.Map[strconv.FormatFloat(f, 'f', -1, 64)]
		if !ok {
			return nil, fmt.Errorf("enum has no entry for %v", f)
		}
		return s, nil
	}
	return nil, fmt.Errorf("unknown convert kind %q", c.Kind)
}

func number(v any) (float64, bool) {
	switch n := v.(type) {
	case float64:
		return n, true
	case float32:
		return float64(n), true
	case int:
		return float64(n), true
	case int32:
		return float64(n), true
	case int64:
		return float64(n), true
	case uint32:
		return float64(n), true
	case uint64:
		return float64(n), true
	}
	return 0, false
}
